### ISSUE TITLE
DAI Archemy

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/wallet#20]
![Screen Shot 2019-04-08 at 10 39 32](https://user-images.githubusercontent.com/4891004/55693583-c131da80-59ea-11e9-85ed-7c3845e367c2.png)

Without no balance, 1000 DAI deposit succeeded.

**Comment by shogochiai** [comment]
I doubt `isOk()` is true even when depositERC20 doesn't substruct balance on L1

https://github.com/cryptoeconomicslab/wallet/blob/68bf90aec74cb97b2f6919dfadf8a004c8331f63/src/redux/modules/chamberWallet/deposit.ts#L105

**Comment by shogochiai** [comment]
@syuhei176 @tkmct Is this bug? Or intentionally not implemented yet?

**Comment by syuhei176** [comment]
I think current DAI's decimal on chamber testnet is too small(maybe 1). I should have set more appropriate decimal. Maybe your 1027 DAI means 0.000...1027DAI

**Comment by shogochiai** [comment]
@tkmct @syuhei176 Could you gimme a way to register DAI on local? I confirmed `wallet.getAvailableTokens()` is reading `tokens` key from walletStroage, but I couldn't reach how can I configure the data.

**Comment by tkmct** [comment]
On local, there are no DAI but there is a TestToken.
There is an account already has TestToken at start up time. getAvailableTokens ask sdk to check tokens deployed on the childChain.

**Comment by syuhei176** [comment]
yes, migration script deploys `100000` TestToken.
https://github.com/cryptoeconomicslab/plasma-chamber/blob/master/packages/contracts/migrations/2_deploy_contracts.js#L56

**Comment by shogochiai** [comment]
More than 100000 test token deposited. This is digit issue.
 
![Screen Shot 2019-04-10 at 10 22 45](https://user-images.githubusercontent.com/4891004/55844969-cf166580-5b7a-11e9-8738-ff57b75855bf.png)

**Comment by shogochiai** [comment]
`1,000,000 Test Token` was in rootchian

![Screen Shot 2019-04-10 at 10 52 38](https://user-images.githubusercontent.com/4891004/55845926-bf008500-5b7e-11e9-95e2-ed526c837bc8.png)

**Comment by shogochiai** [comment]
I found this value is derived from `100,000 * 10 = 1,000,000` at this line.

https://github.com/cryptoeconomicslab/plasma-chamber/blob/master/packages/contracts/contracts/test/TestPlasmaToken.vy#L23-L28

And this part seems irrelevant from DAI Alchemy bug

**Comment by shogochiai** [comment]
I observed `10^15 token = 0.001 DAI`.

Additionally, TestPlasmaToken is `decimal=1`.

So this is caused by decimal inconsideration.

**Comment by syuhei176** [comment]
oh, That was my mistake. I expected decimal=0

**Comment by shogochiai** [comment]
E2E consistency test would be required
https://github.com/cryptoeconomicslab/plasma-chamber/issues/266

**Comment by shogochiai** [comment]
This test would be a good example of a test for this issue. And currency-formatter should be ERC-20 formatter which converts (input number, ticker) tuple into decimal-considered value.
https://github.com/MetaMask/metamask-extension/blob/develop/test/unit/balance-formatter-test.js#L11

**Comment by shogochiai** [comment]
```:js
tokenDict = {
  dai: {
    decimal: 18
  }, 
  test: {
    decimal: 1
  }
}

function format(input, code){
  return input / Math.power(10, tokenDict[code].decimal)
}

format(2.2*10^18, 'dai') 
format(2.2*10^1, 'test')

```

**Comment by shogochiai** [comment]
Close #29
