### ISSUE TITLE
Linter (Wallet)

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/wallet#41]
## Description

Add linter.
- [x] define linter configuration
- [ ] check format pre-commit

**Comment by shogochiai** [comment]
@ackintosh gave us feedback regarding eslint config to the archived repository.
Try not to miss this feedback :)

https://github.com/cryptoeconomicslab/plasma-wallet/pull/54

https://github.com/yannickcr/eslint-plugin-react/pull/1978

**Comment by tkmct** [comment]
this repo has already linter.
And I guess it's better check lint on ci rather than pre-commit.
