### ISSUE TITLE
Emergency Wallet

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/wallet#6]
#plapps largely depends on offchain server for non payment data (e.g. product catalog, feed).

What if the page has been censored? Exit would be tough for the normal users. By adding RPC URL, chamber must capable let customers Exit for any plapps.

---
*plapps: Plasma Apps

https://github.com/cryptoeconomicslab/plasma-chamber/issues/184

**Comment by shogochiai** [comment]
@tkmct is the current wallet implementation has any RPC URL customization form?

**Comment by tkmct** [comment]
currently, no.
Do you mean we need to provide UI for exiting plapps by inputting rpc url?

**Comment by shogochiai** [comment]
@tkmck I rethinked that under such circumstance, community would newly build wallet with replacing rpc url. Never mind.
